### ISSUE TITLE
Bug de responsive en width desde 768px a 1400px

### ISSUE THREAD

**Issue by Nicodc96** [Nicodc96/integrador_cac-front#2]
El texto del header tiene a irse por debajo de la imagen, corrompiéndose en estas medidas. Estuve probando y se podría aplicar estos dos estilos en los **max-width:1050** y mayor que se necesiten.

Adjunto imagen de referencia:
<div align='center'>
<img src='https://i.gyazo.com/eebfa10362036a1055f9cc372016f06c.png' />
</div>

Adjunto código que podría ayudar:
```css
.banner-text{
    top: 250px;
    left: 40vw;
}
```
